[package]
name = "io-backends"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.69.2"

[dependencies]
env_logger = "0.11.1"
log = "0.4.20"
